### ISSUE TITLE
Strong and em tags in activity descriptions?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#475]
In the current spec, is it allowed to include strong and em tags in language maps, specifically in the activity description? Or will reporting tools expect a plain text string?

Is anybody aware of any tools that send descriptions containing html formatting? 

If it's not allowed, should we allow it in a future version? I think this could be helpful, particularly for quiz question descriptions, for example.

**Comment by falcon-git** [comment]
What was the reason for not allowing HTML in language maps? And shouldn't we provide a way to add the HTML version if relevant instead of having the community define different extensions for it? I have customers who uses inline images in their multichoice alternatives. A stripped version of that won't make any sense.

**Comment by garemoko** [comment]
I think this has to do with systems that render the data. If a reporting tool has to worry about images and other html features in what it displays, that presents much more complex layout issues for the report to deal with. 

For purely image based questions, the text which might have been used in alt tags could be used instead. It might also be good to use the moreinfo property to provide a link to a fully rendered version of the question (though I don't know that this property is used by any reporting tools today).

**Comment by falcon-git** [comment]
Ok, but if the problem resides in the LRS shouldn't the LRS solve it? The LRS could strip tags where tags aren't supported and use tags where they are supported?

The images typically won't have useful alt texts since those could be used for cheating. A question like this won't work for a blind person. "Which picture depicts a dolphin?"

**Comment by falcon-git** [comment]
I mean, wouldn't it be better to keep all the data in the statement, and only stip it away where needed?

**Comment by garemoko** [comment]
This is probably worth raising as a new issue as this discussion on a closed issue will likely get lost. 

I can see the value of what you're saying. At this point it most likely can't be added though as it would be a breaking change in the spec.

**Comment by falcon-git** [comment]
Ok, thanks a lot, I've done that #778 :)
