### ISSUE TITLE
Future timestamps

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#511]
The spec says:

> A timestamp MAY be a moment in the future, to denote a deadline for planned learning, provided it is included inside a Sub-Statement.

"provided it" sounds like a MUST, but is an LRS allowed or must it reject statements it considers to be in the future? How do we deal with clock skew, or LRSs that have an incorrect time set for whatever reason.

**Comment by garemoko** [comment]
I'm not sure we need to handle the case of an LRS with an incorrect time set - that's a broken LRS. 

If we add a requirement that the LRS MUST (or SHOULD* in 1.0.3) validate timstamps for future-ness, we could also say they MAY allow some flexibility to account for minor variations in clock times. I don't think we need to specify a precision.

**Comment by brianjmiller** [comment]
It will be hard to test without a precision.

**Comment by garemoko** [comment]
How about a maximum flexibility, so the LRS could enforce greater precision if it wanted to. What would that maximum be? 15 minutes?

**Comment by bscSCORM** [comment]
It sounds like a MUST, but is it a MUST? Have we "turned around" exceptions to a MAY like that before, where without the MAY the behavior would have been allowed?

**Comment by garemoko** [comment]
We actually require this behaviour as a SHOULD elsewhere: ```A timestamp SHOULD be the current or a past time when it is outside of a Sub-Statement.``` - this has been in since 1.0.0 or longer. This MAY is the balancing exception to that SHOULD I think. They should really be positioned one after the other. 

So actually we can't really have the LRS validate this until 2.0 at the earliest, if we want to go down that route, because it might break clients.

**Comment by fugu13** [comment]
I think we should differentiate between SubStatement timestamp and Statement timestamp more clearly (since they're really different animals), so we don't confuse the issue by seeming to refer to the other by exclusion. I don't want the LRS to refuse to accept future timestamps (even with a tolerance), since it absolutely must accept them at least a bit in the future, because clocks aren't reliable enough, and because on misconfiguration (server thinks it's a few hours different, for instance, which happens more than you might think) it's a lot better to accept the (perfectly okay) data than to refuse it.

**Comment by garemoko** [comment]
I still don't agree with supporting the misconfiguration use case, but I agree with the conclusion - making this section clearer and leaving it as a SHOULD so we're not expecting the LRS to validate it.

**Comment by andyjohnson** [comment]
Per the 1/21/15 call:

Sub-Statements are not "real" Statements, so the expectations of TimeStamps don't apply.  (More here in the PR)  TimeStamps for Statements MUST in the past, but LRSs cannot reject Statements based on TimeStamps (because things like clock skew can happen)

**Comment by garemoko** [comment]
I'm not clear on the exact proposed changes here. My understanding is:

1. Move ```A timestamp SHOULD be the current or a past time when it is outside of a Sub-Statement.``` down two requirements so that it's second to bottom on the list. 
2. Re-word ```A timestamp MAY be a moment in the future, to denote a deadline for planned learning, provided it is included inside a Sub-Statement.``` so that it's clear from the start of the sentence that this is about sub-statements. 
3. Change ```A timestamp SHOULD be the current or a past time when it is outside of a Sub-Statement.``` to MUST. I disagree with this one, but it seems to be the consensus from the call?
4. Add some descriptive language to https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details-16 explaining that "Generally timestamps are in the past, but timestamps in sub-statements can be in the future because (explain the reason). For validation purposes, sometimes timestamps will be a little bit in the future because of a lack of synchronisation." 

Is that right?

**Comment by fugu13** [comment]
Hmm, close; I'll take a stab at a PR
