### ISSUE TITLE
Agent Profile API: Clarifications

### ISSUE THREAD

**Issue by jbajou** [adlnet/xAPI-Spec#544]
When implementing this API, I had a few trouble to understand some parts, which means that I may not be the only one struggling. Here are my problems, my thoughts, and I'll provide a pull request so we can move on making all of this more clear.
This follows topic: https://groups.google.com/a/adlnet.gov/forum/#!topic/xapi-spec/uBevRIhHZ3A

1 **I didn't get at the first place that document was actually referring to the document Misc type. (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#miscdocument)**
This could be fixed by replacing "key / document" by "key / Document" in the sentence "The Agent Profile API is much like the State API, allowing for arbitrary key / document pairs to be saved which are related to an Agent."

2 **"If an LRS does not have any additional information about an Agent to return, the LRS MUST still return a Person when queried, but that Person Object will only include the information associated with the requested Agent."**
I didn't feel confident with my understanding of this requirement. In my understanding this implied that the Person Object returned MAY include informations associated with another Agent than the requested Agent. Does this sentence only means that the returned Person Object will contain the field of the requested Agent, and only those fields, if the LRS has no priori knowledge of the Agent ?

3 **Multiple GET**
This endpoint gives us a list of ids. Maybe it would be helpful to be more precise with the id format. I've seen some uuid for this field during my tests, and I'm not really sure if an AP should use an uuid or a human readable id like a filename would do for a file.

**Comment by garemoko** [comment]
@jbajou - are you still planning on doing a PR for this?

**Comment by andyjohnson** [comment]
Consensus on the 2/18/15 call is to make a PR with the language/capitalization adjustments.

**Comment by garemoko** [comment]
On item one, I don't think the capitalisation is warranted or helpful. We link to the document object type at the start of the document APIs section already. This will become even clearer when we re-structure the spec. 

I've made a branch addressing item 2 which I'll PR now. I'm going to tackle item 3 within #645 to avoid a conflict.

**Comment by dacdave** [comment]
This issue is a little stale, so I'll apologize in advance if I should have posted this comment somewhere else.

In section 7.5 of the spec, we are told that any GET request to the "activities" endpoint will return a 200 status and the requested content. We are not told what happens if no such content exists for the requested activity. Conversely, in section 7.6 we are told that a GET call to the "agents" endpoint MUST return a Person object - making one up from the data in the request if one does not already exist.

Issue #690 suggests that we change the spec in section 7.5 to say that a call to the "activities" endpoint should also make one up if no such activity exists.

I disagree. I think that both endpoints should return a null object, an HTTP status of 404, and an operational success attribute of true if no content exists matching the request.

I look forward to your explanations of why this doesn't work.

**Comment by garemoko** [comment]
@dacdave do you mind raising a separate new issue for that? Or perhaps comment on #690 if you think the two are linked enough to need to be discussed together.

I'm hoping this current issue thread can be closed soon as there's an open PR covering the remaining points. 

Thanks!

**Comment by garemoko** [comment]
Is this issue addressed now and ready to be closed?

**Comment by dacdave** [comment]
+1 for closing this issue.
