### ISSUE TITLE
Formatting issue around statement signing

### ISSUE THREAD

**Issue by brianjmiller** [adlnet/xAPI-Spec#597]
It looks like there should be a formatting adjustment for the text: 

`The LRS SHOULD include a message in the response of a rejected statement In order to verify signatures are well formed, the LRS MUST do the following`

The text in the document shows a line break before "In order" where I was originally going to put a period. It looks like it is intended that there be  break before the LRS requirements.

**Comment by garemoko** [comment]
Needs a double space at the end of the line and then probably a line break too to create a gap.

**Comment by garemoko** [comment]
As this is so small, I've bundled it into: https://github.com/adlnet/xAPI-Spec/pull/580

Just adding the line break broke the bullets, so I had to put a bullet before the 'In order to verify' too. I don't think you have have second level bullets in markdown (or HTML?) without a first level and this works fine anyway. End result: https://github.com/garemoko/xAPI-Spec/blob/issue-335/xAPI.md#requirements-19

**Comment by garemoko** [comment]
Looks like this is resolved already by #580
