### ISSUE TITLE
Content of requests in section 7.0 not clear

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#598]
It's not explicitly or clearly stated what the **content** of requests to the Statement API should look like. 

In particular, when POSTing a single Statement, does that Statement need to be in an array? I'd say yes, but I don't see that stated anywhere.

**Comment by brianjmiller** [comment]
See #366 as dupe.

**Comment by brianjmiller** [comment]
The fact that this has come up 2-3 times *at least* as issues, and may have been discussed in other dark corners, it probably should be proposed as a 2.0 change. Perhaps leave this one open with a 2.0 label @andyjohnson?

**Comment by garemoko** [comment]
I *thought* I'd seen this somewhere, but missed that issues because it was closed. I will leave this open. 

For 1.0.3 we can at least make it clear that a single statement without an array is acceptable, but not recommended, so it can have ```patch``` **and** ```major``` labels I think.

**Comment by andyjohnson** [comment]
Yes, oddly we talk about retrieval of Statements (array, even if single), but we do not have provisions for the storage of them that I can find, although I do remember discussing.

**Comment by fugu13** [comment]
Copying some thoughts from a response on the mailing list:

I've always interpreted "Stores a Statement, or a set of Statements" (especially since it dates from when we were much laxer with language) as allowing a single Statement object without wrapping array to be sent via POST, since "a set of Statements" (only expressible in JSON as an array without significant additional explanation) would include arrays of one Statement, and the singular wouldn't be necessary.

**Comment by garemoko** [comment]
It also appears we could be clearer on content and content-type in the document APIs: https://community.articulate.com/discussions/articulate-storyline/storyline-tincan-and-state-api-issue

**Comment by andyjohnson** [comment]
Think this is good, let me know if I am wrong @garemoko
