### ISSUE TITLE
Clarify that 'Basic badAuth' returns 400 not 401

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#600]
See https://github.com/adlnet/xAPI_LRS_Test/issues/23

https://github.com/adlnet/xAPI_LRS_Test/issues/16

I've not actually checked that the spec is unclear on this, but two LRS vendors have been tripped up by it, so even if it is clear, it may be worth adding an extra note or appendix calling out this example.

**Comment by fugu13** [comment]
If an LRS didn't support Basic auth (which is allowed), but did support other forms of auth, then 401 would be a totally acceptable response, unambiguously -- there's no requirement that a server know how to parse a non-understood auth-scheme's parameters.

When an LRS does support Basic, the proper response is somewhat ambiguous by the relevant specs; it definitely isn't a properly formatted Basic credential, but most specs for other HTTP authorization schemes that specify what to do with malformed tokens only put a SHOULD on implementing servers to respond with 400 (see, for example, OAuth 2.0: https://tools.ietf.org/html/rfc6750 "The request is missing a required parameter, includes an unsupported parameter or parameter value, repeats the same parameter, uses more than one method for including an access token, or is otherwise malformed.  The resource server SHOULD respond with the HTTP 400 (Bad Request) status code").

The Basic auth spec is silent on the proper response, but given servers aren't absolutely required to 400 on malformed tokens in other (registered under the same parent spec) Authorization schemes, it's a bit of a stretch to say the only right response to a malformed token for Basic auth is 400. At the same time, it's definitely an acceptable response.

**Comment by garemoko** [comment]
Thats Russell. What I'm taking from that is that we could include a SHOULD along the lines of "If you're using Basic auth, return 400 for malformed credentials".

**Comment by fugu13** [comment]
I don't think there's any need for a should; if we want to include the test in the conformance suite, all it should do is check that the request has a non-success status (that's all that's really required; even a 500 would be weird but not really bad). Some parts of the HTTP specs need to be tested more thoroughly as they're key to what an LRS is, but responding with a very particular status code when it doesn't really matter at all which status code is used since this is bizarrely wrong behavior is far outside our remit.

**Comment by garemoko** [comment]
I do think there needs to be some guidance for LRS vendors based on the confusion we've seen. Maybe it's just descriptive text.

**Comment by fugu13** [comment]
I'd say that if any of the possibilities were wrong, but none are -- if an LRS vendor chooses 400 or 401, they're both fine, and both are supported by the HTTP specs, and even if a vendor 500s because they didn't think to handle the situation and are rolling their own Basic auth (which would be a bit weird), that's okay too (though they'd probably want to fix it for their own reasons) in a sense.

**Comment by garemoko** [comment]
This needs discussion and conclusion. Suggest we pick this up on a call sometime soon.

**Comment by andyjohnson** [comment]
Per the 3/4/2015 call, part of the issue could be a "don't return a 2xx response", allowing 3xx, 4xx, or 5xx.  400 and 401 should cover everything we care about it.  Some extra responsibility for LRS testing because of the way clients would validate against LRSs.  Consistency in error codes is important, but 400 and 401 will both have the code writer looking into the auth token.  Redirect codes and other HTTP codes may be relevant to the point of going beyond what the spec lists specifically as "allowable" codes.  Response codes may need a future discussion, but this issue can be resolved with 400/401.

**Comment by garemoko** [comment]
On the basis of all the discussion, I think we can close this spec issue and just handle it in the conformance suite (adlnet/xAPI_LRS_Test#38)?

**Comment by andyjohnson** [comment]
Agreed, as there is flexibility in error handling, the spec doesn't need to tighten, we just need flexibility in the testing.
