### ISSUE TITLE
numeric interaction correctResponses contain square brackets? 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#603]
The [example definition of a numeric question in appendix C since 1.0.0](https://github.com/adlnet/xAPI-Spec/blob/1.0.0/xAPI.md#numeric) shows the min/max delimiter as ```:```. The new wording we've added for 1.0.3 (not released) follows this. 

My reading of SCORM 2004 4th Ed. is that the delimiter should be  ```[:]```. At least 1 LRS requires this format and rejects statements that don't use it. 

The Golf Tin Can prototype that many adopters use for reference does not use delimiters at all, but just lists the single correct answer as a string. This follows the example of the advanced run time calls example for SCORM 2004 3rd Edition here: http://scorm.com/scorm-explained/technical-scorm/golf-examples/

So which is right? 

My position is that for single answer numeric questions the single value should be allowed without the delimiter, and the delimiter should only be required when there's a range involved, and that the delimiter we've given in the example should stand.

**Comment by fugu13** [comment]
I don't even know any more. This is, what, like the 4th or 5th thing we've found in SCORM where no one ever actually really followed the standard? And this is only in a tiny slice of it! How did anyone ever successfully interact with SCORM implementations?

The SCORM 2004 RTE itself is quite clear that a single value must be value[:]value (the normative language is clear, and they have an explicit example of that sort). But as you say, lots of people using SCORM apparently never followed that, and LMSs sure didn't validate.

I think it is clearly a mistake to have ever relied on the SCORM standard as a source of truth. It is effectively unimplementable, since actual implementations are so far from what the standard says. So, I'm glad we're incorporating explicit language, though in a somewhat distant future (2.0?) we should probably just scrap the weird SCORM string constructs entirely in favor of explicit fields.

We definitely shouldn't write a colon without the brackets in (so we'll need a change for that too); that's just introducing a new bit of weird string formatting that has never been in the SCORM standard even remotely. I'm okay with accepting a single number given the prevalence, but wow, it is going to be a pain to go through all Wax's strict actual-SCORM-RTE validation and make sure we adhere to completely-fudged-real-world-SCORM as conveyed via xAPI. But at least from there we won't be incorporating by reference, which is too bad, because that works fine for most standards.

**Comment by andyjohnson** [comment]
Ugh, confirmed what @fugu13 is saying.  It is a mess either way.  Wonder how so many slipped validation - there are a ridiculous number of tests in the DMI package, a ton with delimiters.

**Comment by andyjohnson** [comment]
Per the 2/4/15 call, Accept and do not modify each variant (not the single ":")   Let APs know that either output could come out.
