### ISSUE TITLE
Are attachments included in signatures? Does order matter?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#634]
The spec says: ``` The JWS signature MUST have a payload of a valid JSON serialization of the Statement generated before the signature was added. ```

Does this logically imply that the signature MUST be the last attachment to be added, and indeed the last property of the statement to be populated by the AP? (So signing the statement and then adding some more context is not allowed). 

I think it does and that we should make this explicit.

**Comment by fugu13** [comment]
I can see the argument for being the last attachment in the array (note that I didn't phrase this in terms of order they're added, but order they exist), though I don't feel that's especially necessary. Given we've specified the arrays are ordered you could make the case the attachment arrays compared could only be equivalent if everything is in the same place, which would at least lightly support the idea of the signature needing to be the last attachment.

I'm not sure what you mean by "the last property of the statement to be populated by the AP"; the statement in the signature must be equivalent to the statement outside the signature minus the signature, no matter what order anything was made in. The order properties are assembled doesn't matter at all, just whether that property holds (though to make sure that property holds the AP should add all properties before signing, since LRSs are allowed to be pretty stringent on the comparison).

**Comment by garemoko** [comment]
"the statement in the signature must be equivalent to the statement outside the signature minus the signature" - obviously this must be true and what the requirement I quoted is trying to say, but it'd be nice to explicitly state this. This is what I was getting at in my issue, but ironically failed to explicitly say!
