### ISSUE TITLE
CORS in the xAPI Spec

### ISSUE THREAD

**Issue by vbudhram** [adlnet/xAPI-Spec#653]
I was looking through the xAPI spec and was hoping someone could clarify the inclusion of [Cross Origin Requests](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#cors). I believe that CORS, being an HTTP spec, does not necessarily belong in the xAPI spec. It should be up to the implementer of an LRS to determine if they want to allow CORS. I think we should reconsider CORS being mandated in xAPI.

I understand that not all clients (Flash and IE8/9) support all the HTTP methods, such as DELETE, PUT and HEAD.  So I propose, that we expand the concept of method overriding using a query parameter such as 'method'. If this query parameter is found, then it will override the request type. Method overriding would exist for all endpoints.

For example, issuing a GET request with method query parameter set to DELETE would override the functionality to be DELETE.
```
http://example.com/xAPI/activities/profile?activityId=asdf&profileId=asdf&method=DELETE
```
Override mapping:
     GET can be overridden by HEAD, DELETE
     POST can be overridden by PUT

Also, I see the advantage of accepting form [POST](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#appendix-g-cross-domain-request-example) directly into an LRS without the need of JavaScript to modify headers and body.  To support form fields, I think we could keep the solution that is already proposed, mapping certain form fields into values usually specified in the header or body but the heading might need to change since I am not seeing the relationship to CORS.

**Comment by brianjmiller** [comment]
Can you point to the part of the spec that requires an LRS to provide the CORS headers?

The alternate method suggestion is already included in the specification though with slightly different configuration. All requests must have method POST, the "method" query parameter is still there, and the other required fields are placed in the body. How is this not sufficient? (ref: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#78-cross-origin-requests)

Doing direct form POSTs will be nearly impossible at this point because of the need for the X-Experience-API-Version header, not to mention the multi-dimensional shape of objects. Converting a form to a JSON object and communicating with an LRS is a *very* low bar at this point with libraries such as TinCanJS (https://tincanapi.com/libraries/) which fully supports IE8/9 (granted Flash is another story, and one unlikely to get much attention).

Brian

**Comment by vbudhram** [comment]
In the section you referenced (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#78-cross-origin-requests), it has a bullet "The LRS MUST support the syntax above." It is also part of the ADL 1.0.2 [conformance testing requirement] (https://github.com/adlnet/xAPI_LRS_Test/blob/master/TestingRequirements.md)

I agree that direct form POSTs will be difficult and it is a low bar with libraries. However, overriding methods for clients that do not support PUT, DELETE, etc, is a different problem than supporting CORS. It just so happens that the CORS implementation for IE8/9, makes a cross origin call. XDomainRequest which does not support DELETE, PUT, while XMLHttpRequest (Not CORS) does support the methods.

It seems like this section is solving independent problems. CORS in IE, Method overriding, and form submission. We should solve for these problems but they are independent and could be broken up into different pieces.

Maybe we can change the title of that section to be more generic so that it covers different types clients not just IE. Client's that don't have CORS but still can't use all HTTP methods.

Let me know what you think.

**Comment by garemoko** [comment]
Side note re Flash - one use case of Flash is apparently Adobe Connect plugins which use pure flash and can't call JavaScript. I don't believe this requires a spec change though as somebody is already doing this. 

I'm struggling to see what change is being proposed in this issue. 

* Is it just allowing requests other than POST to use the method parameter? If so, why? What's wrong with POST? 
* Is it just changing the title of that section? Is so, what would you change it to?

**Comment by brianjmiller** [comment]
I believe (note intentional subjectivity, I can be proven wrong) the bullet is indicating that the "IE Mode Request" syntax must be supported, in other words, the "method" parameter. It doesn't indicate that CORS itself has to be supported which I agree is a different technical problem. (Though I don't know why an LRS wouldn't set the headers necessary other than laziness, as it is easily subverted with a proxy.)

Is there a non-IE 8/9 reason to support method overriding (other than direct form posts)? It seems like renaming the section to "IE Mode Request" (or something better) is all that is needed. Any language around CORS and http vs. https could be dropped or is at best a side note based on a single browser's in two versions deficiencies, both of which are hopefully starting to dwindle in usage, and there is good library support for them already.

I'm still :-1: on direct form posts, the only use case is a browser one and I think it is pretty weak at that.

**Comment by DavidTPate** [comment]
For non-IE 8/9 you would need to support Flash. It has a 2 main restrictions on what it can do related to this.

1. It only supports GET/POST
1. Headers can only be set with a POST

So a GET for example wouldn't be able to be send the required xAPI version header without doing a POST with a method override. Allowing these parameters to be set via a Query String or Headers would be ideal to allow that support.

Additionally, some older HTTP clients (older versions of Apache's HTTP client comes to mind) don't support the additional methods and have restrictions on headers too.

**Comment by brianjmiller** [comment]
@DavidTPate the current spec should support this. It is possible to specify POST for a request with a "method=GET" parameter and all other relevant parts of the request including headers are then placed into the body of the request as a form would do. AFAIK the only restriction left is that attachments with attached files are impossible because there is no accounting for a multipart request.

**Comment by fugu13** [comment]
I'm probably missing something, but I don't see any reason off the top of my head attached files shouldn't work, just burrow the content-type header along with. and treat the content as stated. Oh! yes, I see, binary attached files won't work (encoding problem), but purely non-binary attachment payload should be fine.

**Comment by brianjmiller** [comment]
Frankly I was thinking that as well, but for whatever reason I trusted this:

"Attachments: Sending attachment data requires sending a multipart/mixed request, therefore sending attachment data is not supported with this syntax." (spec ref: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#detailsrequirements)

**Comment by fugu13** [comment]
*nods* yeah, it definitely isn't that that's the limiting factor, as content-type can be burrowed just fine, but the binary data question. We should remove it and replace it with more accurate language.

**Comment by garemoko** [comment]
Here's my attempt at setting out what needs to be done to resolve this issue:

* Rename ```7.8 Cross Origin Requests``` to ```7.8 Alternate Request Syntax```
* Update the anchor name and any links to match. 
* Replace ```Sending attachment data requires sending a multipart/mixed request, therefore sending attachment data is not supported with this syntax.``` with ```Note that due to issues relating to encoding, it is not possible to send binary data attachments using this syntax.```

**Comment by garemoko** [comment]
Can this be closed now?

**Comment by vbudhram** [comment]
Yea I think its good to be close.

**Comment by garemoko** [comment]
@andyjohnson or @vbudhram please press the close button. :-)
