### ISSUE TITLE
URI equality and case sensitivity

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/xAPI-Spec#69]
We should add explicit language to avoid ambiguity when comparing URIs such as:

http://example.com/foo/bar
http//example.com/FOO/bar
http//EXAMPLE.com/foo/bar

According to the URI spec, 1 and 3 _are_ identical, but 2 is different from 1 and 3. (the host name part of a URI is case insensitive, the rest is case sensitive.

This is likely enough to be overlooked we should add some "MUST" language to ensure all systems handle URI equality the same way.

**Comment by bscSCORM** [comment]
Note: the .NET `Uri` class will canonicalize URIs by default: https://msdn.microsoft.com/en-us/library/system.uri.tostring%28v=vs.110%29.aspx

We've seen some multiple casings of what was clearly intended to be the same IRI show up as a result of this, and while I still agree requiring a level of IRI equality comparison beyond equal string comparison, I'd like to make sure we don't forbid comparison based on a canonical form.

@andyjohnson I'm not sure if this comment merits re-opening the issue or not, since I'm just suggesting we _don't_ change something.

**Comment by oconnetf** [comment]
`Uri` _also_ adds a trailing '/' if one is not included in the string constructor, which introduces a subtly different problem from casing.

**Comment by bscSCORM** [comment]
After some more internal discussions, and a case where we're tempted to do more than a plain string comparison, I'd like to have a `SHOULD*` around how to compare IRIs, either for a string comparison or specific exceptions to that rule (perhaps the case of the host name), to ensure interoperability.

**Comment by garemoko** [comment]
@andyjohnson please add a patch label so this doesn't get missed. 

Suggested requirements based on the discussion above (we can figure out where to put these later):

* URIs SHOULD* use a lowercase host and scheme. 
* When comparing URIs, the LRS SHOULD* treat the host and scheme as case insensitive.
* When comparing URIs, the LRS SHOULD* treat the path, query and fragment as case sensitive.

CC: @bscSCORM @fugu13 

Am I right to assume that case sensitivity doesn't apply to ports? I've only ever seen numbered ports but wouldn't be totally surprised if somebody had come up with emoji ports or something...

**Comment by brianjmiller** [comment]
I like the suggestions above, but they do not address the other canonicalizations, particularly the '/' one.

**Comment by garemoko** [comment]
@brianjmiller 

* URIs SHOULD* end with a '/' character. 
* When comparing URIs, the LRS SHOULD* treat URIs ending in a trailing slash as equivalent to those that don't. 

Or should that be SHOULD* not?

**Comment by garemoko** [comment]
This thread has referred to URIs, but do we mean IRIs? If yes, I propose that these new SHOULD*s go here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#metadata-provider-requirements

Another candidate for a location for these requirements is: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#statement-immutablity-and-exceptions where we already say "Some properties are case insensitive and changes in case therefore do not affect immutability. For example, the domain portion an e-mail address is case insensitive. It is recommended to use lowercase for any case insensitive text."

**Comment by garemoko** [comment]
From call: 
* IRIs not URIs
* SHOULD* not end in a slash
* Add to metadata requirements

For endpoints i's already clear that no slash should be included on the end as none of the examples have them. We just need to cover IRIs.

**Comment by garemoko** [comment]
Also add link to https://adl.gitbooks.io/companion-specification-for-xapi-vocabularies/content/vocabulary_development_and_publishing/iri_design_and_persistence.html

**Comment by fugu13** [comment]
The problem with the individualized recommendations is that the strong best practice for URIs and IRIs is code either does pretty exacting normalization or no normalization whatsoever.

Some of the recommendations stated as optional above, also, are not optional per the URI/IRI specs, such as "When comparing URIs, the LRS SHOULD* treat the path, query and fragment as case sensitive."

This is not something the LRS has an option on. The path, query, and fragment are case sensitive in URIs & IRIs (except for the case of hexadecimal characters used in escape sequences), full stop. If an LRS is treating the path, query, or fragment as case sensitive, they are violating the URI/IRI specs, which are expressly cited as the standard by the xAPI spec, and thus violating it as well.

For another, "When comparing URIs, the LRS SHOULD* treat URIs ending in a trailing slash as equivalent to those that don't."

This should be a SHOULD NOT, or rather, it is already a MUST NOT by incorporation, since the specifications are very clear that URIs/IRIs that differ by a trailing slash are different, not the same, and should only be maybe normalized together if, when one resource is accessed, it permanent redirects to the other.

My recommendation is to adopt the following requirement:

> When storing or comparing IRIs, LRSs SHOULD* handle them using one or more of the approaches described in 5.3.1 (Simple String Comparison) and 5.3.2 (Syntax-Based Normalization) of RFC 3987, and SHOULD* NOT handle them using any approaches described in 5.3.3 (Scheme-Based Normalization) or 5.3.4 (Protocol-Based Normalization) of the same RFC, or any other approaches.

The latter part's just to make really clear what people should not be doing; technically only the SHOULD* part is needed.

I realize this lets different LRSs handle IRIs differently; given how typical that is in IRI implementations, and how simple (and preferable) the solution (send character-by-character equivalent IRIs, which are guaranteed to be matched), I'm pretty okay with it. If people feel otherwise, we should adopt a specific list of the normalizations listed to SHOULD* (I'd recommend all of the ones in 5.3.2).

**Comment by fugu13** [comment]
A link straight to the comparison section of the IRI RFC: https://tools.ietf.org/html/rfc3987#section-5.3

**Comment by garemoko** [comment]
@fugu13 that looks like a well thought through requirement on the LRS side. 

I'd also like to add requirements on metadata providers and learning record providers to attempt to avoid Syntax-Based Normalization yielding a different result to Scheme-Based Normalization. Looking at the discussion above and list in 5.3.2 of RFC 3987 this means:

When re-using an existing IRI:
* Using character-by-character equivalent IRIs 

When coining a new IRI:
* Using all lowercase
* Not ending in a slash
* Not using special characters
* Percent encoding where appropriate
* Not using dot segments. 

Arguably the "when coining a new IRI" list belongs in Jason's companion doc rather than the spec itself.

**Comment by fugu13** [comment]
I'm broadly okay with the concept of having some (more) recommendations for people designing IRIs, though I'm not quite sure what you mean or your goals are by "avoid Syntax-Based Normalization yielding a different result to Scheme-Based Normalization".

Ending in a slash isn't a big deal, they just need to do it or not consistently (if they're mapped to the same location). Additionally, I think the concept of not using special characters counters many of the goals of allowing IRIs -- if we're being welcoming to flexible identifiers suitable to global use, we should be welcoming. The percent encoding thing is sort of similar; there are times that's definitely the right choice, and times it makes more sense not to (and sometimes a programming library being used will make one or the other more natural).

Definitely agree on recommendations to use lowercase (meant broadly, not as a technically specific requirement -- this is a more difficult thing to specify than it often seems) and not using dot segments (they're mostly silly outside of relative references). 

Ultimately, it doesn't matter too much how someone constructs an IRI, so long as they ensure that, in cases where they intend them to be the same, they are the same (vis Simple String Comparison).

**Comment by garemoko** [comment]
Absolutely take the point on special characters. 

The goal with recommending whether or not to use a slash or % encoding is to help people to do it consistently with one another when using the same IRI. I.e. if all coined IRIs have no slash on the end people will be less likely to get it wrong.

**Comment by fugu13** [comment]
I don't think there's a likely scenario where recommending on the slash helps much, if at all. If anyone is copying an IRI from somewhere (such as for a verb or activity type), they should copy it exactly and nothing else. If anyone is writing software that fills in an IRI, they're pulling out the IRI from what's happening using code, and if they're using code, there are going to be lots of times where attempting to follow such a suggestion will lead to more harm than good.

As an example, if they're in some sort of CMS, those generally offer a function to retrieve a canonical URL for the current page. It doesn't really matter to the LRS or anyone else whether that URL has a slash, and someone seeing a recommendation for it to have a slash and attempting to implement the logic to guarantee such is honestly more likely to mess up a little and introduce problems than they are to help the situation.

**Comment by garemoko** [comment]
Hmm.. Yes that's a valid scenario. I guess that could potentially apply to all the recommendations including case (I'm not aware if any CMSs use case sensitive, capitalized urls, but I guess it's possible)

Ok. So I'm sold that the list of 'When coining a new IRI' recommendations don't belong in the spec. We can argue about whether or not each of them is actually a good recommendation in @jhaag75's companion doc separately.

**Comment by garemoko** [comment]
PR up. Lets continue the discussion there: https://github.com/adlnet/xAPI-Spec/pull/902

**Comment by jhaag75** [comment]
+1

**Comment by garemoko** [comment]
#902 merged. Can this be closed @bscSCORM ?
