### ISSUE TITLE
Result duration precision

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#696]
On the topic of result duration precision we say ```Formatted according to ISO 8601 with a precision of 0.01 seconds``` in the description in the table. 

It's not clear here whether that's a minimum, maximum or absolute and what should occur in the event of greater precision being given (is the precision ignored or is the statement rejected; presumably the statement is rejected). In the example long statement in Appendix A uses 'PT1H0M0S' i.e. second precision.

In terms of real world adoption, there are certainly activity providers using less than 0.01 second precision; I've not seen any using millisecond precision. LRSs seem to support millisecond precision as our recently updated Golf Prototype incorrectly uses millisecond precision and I'm not aware of any LRS that rejects it's statements. I'm planning to update the Golf Prototype, but want to see the outcome of this discussion first. 

I also think that 0.01 seconds is a bit weird and that millisecond support would make more sense as most systems track time in milliseconds. 

I'd like to propose that for spec version 1.0.3 we clarify that the ```precision of 0.01 seconds``` in duration is a SHOULD for clients to provide a *maximum* of 0.0.1 seconds precision. If they provide more, the LRS won't reject, but consumers of the data might not observe the additional precision. We can then plan to change that SHOULD to a maximum of millisecond precision in 1.1.0.

Note that as we've already said that duration has to be considered a string for comparison purposes, the LRS will have to store whatever precision it's sent. 

Thoughts?

**Comment by brianjmiller** [comment]
Most likely the statement would not be rejected as it is not for 'timestamp' as well, where the spec is a bit more clear: "A timestamp MAY be truncated or rounded to a precision of at least 3 decimal digits for seconds (millisecond precision MUST be preserved)." So I'd expect us to treat it the same where an LRS may maintain more precision, but that clients can't count on it to work across all LRSs with some either truncating or rounding. I'm :+1: to millisecond precision here (though that becomes a 2.0 issue), but :-1: to rejection and :-1: to a maximum precision unless we follow suit with 'timestamp' as well.

**Comment by garemoko** [comment]
Good idea to look at timestamp. I can see adding similar language but with 2 decimal digits makes sense for duration. 

I wonder if in 1.0.3 we could get away with saying that the LRS SHOULD* support 3 decimal digits and MUST support 2? If we assume that LRSs have applied the pattern of that timestamp requirement to duration, then this is just a change of emphasis and not of possible behaviours.

**Comment by andyjohnson** [comment]
My interpretation of the ISO is that you agree upon the level of precision, which we decided to be hundredths of seconds.  I would say the LRS MUST trim any extra duration off otherwise we risk immutability issues if some LRSs store too many places.  I don't think rejection is necessary, but is the 2nd best option compared storing inconsistent place values and expanding immutability to duration .  I'm fine with changing to milliseconds instead, as old Statements would still be fine.

**Comment by fugu13** [comment]
I don't see any need to force trimming. That two LRSs have slightly different precisions for duration values does not cause immutability problems, as there's no real issue with comparison (just compare the required-to-keep part to verify they're identical within the tolerances of the spec).

On another note, duration precisions really shouldn't be expressed in terms of units of time, that slipped by me before. The decimal places can only be on the last element in a given duration, but they can be on any element. For example, a duration can be for 1 month, 3.25718 days. It'd probably be better to just say that LRSs must keep at least the last N decimal places on the fractional value if they exist.

**Comment by garemoko** [comment]
@fugu13 expressing in terms of decimals places sounds sensible, but is that a breaking change? 

I'm also wondering if since we've already established that durations have to be compared as strings, should we just allow any number of decimal places? Thinking out loud a little here.

**Comment by fugu13** [comment]
I think its good to give LRSs a little cover to truncate decimal places (also provides a minimum standard of comparison), so maybe not require keeping them all. I think the current setup gives enough cover for keeping them all (it definitely has a precision of 0.01 seconds -- it just also has more precision ;) ), which is what I recommend LRSs to lean toward.

**Comment by andyjohnson** [comment]
Per the 5/6/15 call - Fractional precision should be the same for ANY unit of time.  Fine with moving to 3 decimal places.  Can't be for 1.0.3.  Could give LRSs coverage to keep more digits - in a future version they may be reduced.

**Comment by garemoko** [comment]
From Ben's call notes: for 1.0.3 note that LRSs MAY keep additional precision

**Comment by coltivare** [comment]
In the [ADL xAPI RMF Accreditation Project (xRAP) Final Project Report / Test Results](https://adlnet.gov/publications/2021/07/adl-xapi-rmf-accreditation-project-final-report/), it appears that the precision has not been adjusted to 3 decimal places as suggested above, and still explicitly references seconds precision rather than to precision of the smallest value represented as a decimal fraction. 

> From Section 4.2.7
> When comparing Durations (or Statements containing them), any precision beyond 0.01 second precision shall not be included in the comparison.

I don't have a strong opinion about making this requirement more generic to cover other values than seconds, but I would like to put in a vote for switching to 3 decimal places. One of the reasons for this, is that when dealing specifically with seconds, most languages with robust date/time/duration support handle seconds precision in terms of milliseconds or nanoseconds, and there is often built in support for truncating the precision to milliseconds.
