### ISSUE TITLE
Proposed Document Structure for 1.0.3

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#697]
Revision History (current 1.0)
Contributors - (current 2.1, 2.2, 2.2.1, 2.2.2)
License (stays the same)

Table of Contents

1.0 - Vision/Summary of xAPI Capability (some of current 2.0) and some more high level
2.0 - About this Spec (new intro text, if any)
	2.1 - How to read - (current 2.3)
	2.2 - as a Specification (new)
2.3 - as a JSON-binding (new)
	2.3.1 - Serialization (new)
	2.3.2 - Requiring Values/Non-empty values (new)
2.4 - as a RESTish Web Service
2.5 - Definitions - (current 3.0)
2.6 - How the pieces fit  - LRSs, Endpoints, etc. (new, diagrams also needed)
2.7 - Profiles and Communities of Practice (new)
	2.7.1 - Processes around coining (4.1.3.2)
3.0 - xAPI Data (throw in current 6.1, encoding here, maybe expand?)
	3.1 - Requests (done to each endpoint, see each specific endpoint in data transfer for details)
		3.1.1 - Types (current 7.11)
		3.1.2 - Headers (current 7.2) (consider the format in 6.2)
		3.1.3 - Alternate Requests (current 7.9)
	3.2 - Documents (current 7.3)
	3.3 - Statements
		3.3.1 - Intro + Purpose (new)
			3.3.1.1 Format (current 4.1.12 Client)
		3.3.2 - Statement “Lifecycle”
3.3.2.1 Immutability (current 4.1)
3.3.2.2 Voiding (current 4.3)
3.3.2.3 Exceptions (current 4.1)
		3.3.3 - Structure (current 4.1 table, 4.1-4.10)
		3.3.4 - Querying Statements (current 4.2)
		3.3.5 - Signing Statements (current 4.4)
		3.3.6 - Extensions (current 5.3)
		3.3.7 - Language Maps (current 5.2)
	3.4 - Attachments (current 4.11) *This could move, but I’d like to try it out here
	3.5 - Metadata (current 5.4)
		3.5.1 - IRI Metadata 
		3.5.2 - Activity Definitions (partial duplication for disambiguation)(current 4.1.4.1)
		3.5.3 - Provider/Consumer Requirements
	3.6- Special Data Types
3.6.1 UUIDs
	3.6.2 ISO 8601 timestamps
	3.6.3 8601 durations
	3.6.4 lang codes
	3.6.5 IRIs
	
4.0 - Data Transfer (current 7.0) - discuss endpoints and sub-APIs (new)
	 4.1 Sub-APIs (each will list the allowed methods and expectations as current)
		4.1.1 Statement (current 7.3)
		4.1.2 State (current 7.5)
		4.1.3 Agents ((current 7.7(half))
		4.1.4 Activities (current 7.6 (half))
		4.1.5 Agent Profile (current 7.7(half))
4.1.6 Activity Profile (current 7.6 (half))
4.1.7 About (current 7.8)
5.0 - Data Validation (all LRS requirements)
	5.1 Basics (current 7.10  and 4.1.12)
	5.2 Concurrency (current 6.3)
	5.3 Error Codes (current 7.1)
	5.4 Responses to Requests (current 7.11)
6.0 - Security- some note that sets of permission can be restricted from above.  Not all operations are allowed for all users (current 6.4)
	6.1 OAuth 1.0 Details (current 6.4.1, 6.4.2)
7.0 - Versioning (current 6.2)
<Appendices> (all stay as they are)

**Comment by garemoko** [comment]
Thanks for putting this together Andy. This looks broadly in the right direction, but as always I have some comments:

* There's a reasonable number of new sections. Is it worth doing the re-structure before adding these but perhaps keeping them in mind and then adding them separately later? Could some of this content go in README.md instead? 
* I worry about moving 'statements' down a level as we already struggle with sub-headings within the statements section. What if instead bring documents up a level? I'm not keen on Attachments being the same level as statements. The other option to give us an extra heading space is to split things across multiple linked markdown documents. The same concern applies to the 'sub apis' section. 
* Section 5 is likely to still include a lot of client requirements unless we do a good bit more untangling. 

When we get onto looking at the details, I wonder if this might be easier to review and comment on as a Google Doc or something?

**Comment by andyjohnson** [comment]
To respond to your points @garemoko 

1)  While a lot of these sections are labelled "new", the fact is many are going to just be a short paragraph, of which the text is likely in the spec somewhere already.  The problem with READMEs is that people don't read them :)  The extra wording will be light!

2)  I like the idea of moving Statements up a level, maybe put it ahead of the xAPI Data section and label it "Other xAPI Data Types" and could then expand on 3.6 in there as well.  Both Requests and Documents would also be moved up and be before Statements.  What do others think?

3)  It may, but my hope is in the data sections is to really differentiate the MUST requirements and then have a "catching" requirement in 5.0 that says if the format of X is off, the LRS MUST catch it and deal with it.  Short of changing the spec to being role-centric, I really am not sure how to deal with it.

I think for the first few iterations once this becomes a branch, Google Docs will be the ideal place.

**Comment by garemoko** [comment]
I've added some further comments in the [Google Doc](https://docs.google.com/document/d/1LpciScIP-zoiCOqGCH-d95ETkxxxi9te4w7reAkC4hs/edit). There's one section thats missing in the new structure (7.4) which I've flagged up. It's worth you having a run through the spec and make sure nothing else is missing. 

In terms of process to make sure we don't end up changing something during the reordering, I suggest we do all of the re-ordering simply as cut and paste with no changes at all (even to section numbers or contents) first. If we do each cut and paste as a single commit, this'll make is easier to review and confirm the cut and paste has been done right. Once we've confirmed all the cut and pasting, we can then do all the editing of section numbers and once that's done, then do any further editing to make sure content fits in its new location. 

I do like the suggestion of doing this all in a separate reorganization branch. If the reorganization does end up being a bigger beast than we thought, we can always release the pre-reorganization version as a 1.0.3 and save the reorganization as the first (or only) task in 1.0.4.

**Comment by garemoko** [comment]
Following on from @fugu13's suggestions about no additions or deletions, just moves, the ideal scenario for me would be that the first iteration of this has a one to one ratio between commits and cut and pastes.

This will lead to a lot of commits, but means we can step through the commit history and see exactly what moved where to make sure nothing was lost and nothing duplicated. We could then squash the commits after its been reviewed if that's desirable.

**Comment by garemoko** [comment]
I've been through the commits on the restructure branch up to and including https://github.com/adlnet/xAPI-Spec/commit/455dc60ae7841c321dac1649ca5a78114e531b5b and made comments. The goal of this was to check that nothing had been deleted or added aside from headings. Here's the comments:

* https://github.com/adlnet/xAPI-Spec/commit/889ecccb882d2a7ca757641f6cc2dc109ab99e38#commitcomment-11682347
* https://github.com/adlnet/xAPI-Spec/commit/2510d442f22260a2d734b1347289ce263a3ae0c5#commitcomment-11682544
* https://github.com/adlnet/xAPI-Spec/commit/4acd8d740e13c609089e3e2cd15e0b1a75f21471#commitcomment-11682650 (this one is not worth reading, that commit is fine)
* https://github.com/adlnet/xAPI-Spec/commit/e7d9d77307b8505a4d81526d69c5d26185a27afd#commitcomment-11682755

If anybody wants to replicate, my process was to take the both and after markdown, order both alphabetically and then compare line by line. Obviously you lose the context with this method, but it does flag up non-move differences. 

This is just checking that @andyjohnson didn't make any mistaken deletes or duplications (and it seems like aside from 1 anchor he didn't - well done Andy!). Next steps are to look at the end result and how it's been reordered. 

Note that there were also a lot of changes to blank lines that I didn't comment on.

**Comment by garemoko** [comment]
Comments on the doc as a whole:
* +1 to using h1 for the 'part' headings'. 

* For some of the new headings it's not always obvious what will go in those headings. I suggest adding some clearly marked (maybe in ```code```) non-final summary text in these after this first round of review so we can see what these sections are for before spending a lot of time writing the contents. 

* We haven't achieved the division between data structure and data transfer. Specifically, Part 2 section 1 IMHO belongs in part 3. 

* I think Statements should be before Documents. 

* There's a few comments in the Google doc from me that haven't been resolved e.g. You've put the current section 7.3 for documents in part 2, but that should be in part 3 as it's about data transfer of documents. 5.1 covers the data model of documents. 

* Also my comment about language maps (and extensions) not belonging under statements needs to be considered. 

* I don't like the term 'Sub-APIs' - I appreciate this is already in the text, but I'd rather get rid of it in the text instead of add it to a heading. We should use "resource" instead. Related - I prefer 'About Resource' to 'About API'

*Should concurrency fall under 'Data Validation'? I think yes (as you have done) but I'm not sure so flagging for discussion. I'm also not sure about error codes under validation as not all errors will be validation errors. Versioning certainly doesn't fit. Maybe the section needs a different title. 

* The Appendices should have their own part level heading (h1)

* We still need to check that line break changes have not broken things. See for example: https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#095-to-100-april-26-2013 I'm not sure of an easy way to do this. 

* Links in the TOC are broken by heading changes. There may be links in the body of the document that are also broken. 

That's me done for now. Hope that helps!

**Comment by andyjohnson** [comment]
Thanks so much, Andrew, for the comments and lookthrough!

To address the points:


   - I think the structure of a request in Part 2 is important.  The usage
   will come out in Part 3 for the specific endpoints.  I'd like others to
   weigh in on this too, though!
   - Statements are the most important data structure, but I would like to
   make the Web API portions of this the more prominent part of this
   section...at least in order since the sheer size of the Statement structure
   makes it #1.  I don't think there is any mention of one in the other.
   - So I had intended to split in half, part for describing what a
   Document was in Part Two, then the LRS requirements in Part Three.  Turns
   out the current section is almost all LRS-centric, so you were spot on to
   have it all below.  The document has been restructured to accommodate (I'd
   say the argument for Document before Statements makes more sense in the
   context of how the language in Part 3 Section 1 lays out).  I've left some
   fragments in Part Two as placeholder text.  I suspect it will be quite
   short.
   - Language Maps and Extensions - totally missed that comment.  Language
   Maps is misplaced, 100% agree.  The current extensions section, as written,
   only addresses extensions to the Statement, so I think most of that should
   still be in the Statement.  However, I agree that the concept of extensions
   as well as basic how-tos should be in the Miscellaneous Data Types
   section.  For now, I've completely replicated it.  Will add other language
   in this next iteration to see what should stay and go.  (2nd commit has
   these changes)
   - Not one of yours, but I totally missed the other data types.  I'll get
   to populating this with copied text from the relevant sections.  I didn't
   want to risk deleting these specifically from where they were, but I should
   have duplicated.
   - I am totally fine calling all of the Sub-APIs Resources instead of
   APIs in the headings.  How do others feel (to comment on the tcomment on
   the About Resource, I'll normalize all of these together with what we
   decide)
   - I hate the title "Data Validation" as well as some of the others.  I
   like what is in the bucket, but would appreciate help on brainstorming
   better names ( I don't like Part Three's name, either)
   - Righto on the Appendices' headings, see 3rd commit
   - I'm also afraid of line break changes, but I am aware of it when
   adding text.  Hopefully this doesn't become an issue.
   - The TOC is not in good shape atm!  Will fix it in this next iteration
   :)

Thanks!

Andy

On Mon, Jun 15, 2015 at 12:08 PM, Andrew Downes <notifications@github.com>
wrote:

> Comments on the doc as a whole:
>
>    -
>
>    +1 to using h1 for the 'part' headings'.
>    -
>
>    For some of the new headings it's not always obvious what will go in
>    those headings. I suggest adding some clearly marked (maybe in code)
>    non-final summary text in these after this first round of review so we can
>    see what these sections are for before spending a lot of time writing the
>    contents.
>    -
>
>    We haven't achieved the division between data structure and data
>    transfer. Specifically, Part 2 section 1 IMHO belongs in part 3.
>    -
>
>    I think Statements should be before Documents.
>    -
>
>    There's a few comments in the Google doc from me that haven't been
>    resolved e.g. You've put the current section 7.3 for documents in part 2,
>    but that should be in part 3 as it's about data transfer of documents. 5.1
>    covers the data model of documents.
>    -
>
>    Also my comment about language maps (and extensions) not belonging
>    under statements needs to be considered.
>    -
>
>    I don't like the term 'Sub-APIs' - I appreciate this is already in the
>    text, but I'd rather get rid of it in the text instead of add it to a
>    heading. We should use "resource" instead. Related - I prefer 'About
>    Resource' to 'About API'
>
> *Should concurrency fall under 'Data Validation'? I think yes (as you have
> done) but I'm not sure so flagging for discussion. I'm also not sure about
> error codes under validation as not all errors will be validation errors.
> Versioning certainly doesn't fit. Maybe the section needs a different
> title.
>
>    -
>
>    The Appendices should have their own part level heading (h1)
>    -
>
>    We still need to check that line break changes have not broken things.
>    See for example:
>    https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#095-to-100-april-26-2013
>    I'm not sure of an easy way to do this.
>    -
>
>    Links in the TOC are broken by heading changes. There may be links in
>    the body of the document that are also broken.
>
> That's me done for now. Hope that helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/697#issuecomment-112122032>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by garemoko** [comment]
The point in the IEEE discussions was that potentially the data structure might be useful on it's own for some use cases (I don't recall any actual use cases set forward - @aaronesilvers ?). I think this is also true for people using libraries though. They don't need to understand the data transfer, headers etc. as they just call a function in the library. They do need to understand the structure of statements and other objects. 

You make a good point about the size of the statement section; happy for doc section to stay first. 

On duplicated text, I added some comments on relevant commits. I don't think we should duplicate any text, even temporarily as it could get missed coming out or edited in two different directions so we end up with overlapping but not identical text. This is going to be very difficult to maintain as we will forget that the text is duplicated and only make a change in one place. Instead, where something is relevant in multiple places we should reference it. 

Agree that there's a strong argument for including extensions in the statement section, and then perhaps referring to the concept elsewhere. 

Instead of 'Data Validation', how about 'Data Storage and Retrieval'?

On the Appendices, what i meant was to add an additional h1 heading at the start of the appendices section, rather than make them all h1. Sorry that obviously wasn't clear!

**Comment by andyjohnson** [comment]
The data transfer and header additions will be light and quite conceptual.
Not introducing any new requirements or deep concepts.

Totally agree on the duplicated text - I'm just playing by the rules of
engagement now in that we have no new text until after today's meeting :)
 It is just placeholder now with one section in each case keeping dominance
and the other having some flavor text and a reference.

Will throw 'Data Storage and Retrieval' in with a commit and fixing the
Appendices.  I like your idea better of all h2s.



On Wed, Jun 17, 2015 at 6:40 AM, Andrew Downes <notifications@github.com>
wrote:

> The point in the IEEE discussions was that potentially the data structure
> might be useful on it's own for some use cases (I don't recall any actual
> use cases set forward - @aaronesilvers <https://github.com/aaronesilvers>
> ?). I think this is also true for people using libraries though. They don't
> need to understand the data transfer, headers etc. as they just call a
> function in the library. They do need to understand the structure of
> statements and other objects.
>
> You make a good point about the size of the statement section; happy for
> doc section to stay first.
>
> On duplicated text, I added some comments on relevant commits. I don't
> think we should duplicate any text, even temporarily as it could get missed
> coming out or edited in two different directions so we end up with
> overlapping but not identical text. This is going to be very difficult to
> maintain as we will forget that the text is duplicated and only make a
> change in one place. Instead, where something is relevant in multiple
> places we should reference it.
>
> Agree that there's a strong argument for including extensions in the
> statement section, and then perhaps referring to the concept elsewhere.
>
> Instead of 'Data Validation', how about 'Data Storage and Retrieval'?
>
> On the Appendices, what i meant was to add an additional h1 heading at the
> start of the appendices section, rather than make them all h1. Sorry that
> obviously wasn't clear!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/697#issuecomment-112750174>.
>



-- 
Andy Johnson
ADL Technical Team
608-318-0049

**Comment by canweriotnow** [comment]
I want to ragequit the internet. 

Not relevant, just sayin'.

**Comment by aaronesilvers** [comment]
@garemoko The rationale for separating out the data model (what information constitutes a statement and the nomenclature for it's data model elements) from the data binding (in our current case, JSON) is to allow for (eventually) other data bindings to be employed. The first two obvious examples are XML, for whom there are legacy systems that may be easier to retrofit into using xAPI if XML is an option and low energy bluetooth, specifically for sensors, beacons and other tiny processors for which the payload to form and deliver JSON is simply too taxing to be effective.

**Comment by aaronesilvers** [comment]
@canweriotnow Not sure where the rage is coming from. Might I suggest GIFs for more cheeky and universally understood responses... 
![50127__safe_applejack_animated_rope_haters gonna hate](https://cloud.githubusercontent.com/assets/1231537/8271538/5c60e29e-17eb-11e5-8ab6-9dd2d18b1c6c.gif)

**Comment by aaronesilvers** [comment]
For the record, all ur +1s are belong to us for what I believe is the first GIF comment on an xAPI-Spec thread...

**Comment by canweriotnow** [comment]
@aaronesilvers :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: because PONIES!!!

**Comment by canweriotnow** [comment]
@aaronesilvers 
> The rationale for separating out the data model (what information constitutes a statement and the nomenclature for it's data model elements) from the data binding (in our current case, JSON) is to allow for (eventually) other data bindings to be employed.

There's a practical way to deal with an intractable lack of comprehension for the need of add'l data-bindings, while also dealing with the clients that would require them; we've been doing this with wearables, beacons, etc., through the time-honored tradition of **throw more metal at it!**

When one can't be bothered to reduce the space or time complexity of a procedure, thank's to Moore's law, we can now just throw more hardware at the problem for pretty cheap. Hence, when dealing with tiny BTLE devices, have them speak xAPI through a device that makes a Cray-1 look like a pocket calculator, fits in a pocket, and can run Java. 

I wish there was an animated GIF to convey this... I'm probably not looking hard enough... *le sigh*

**Comment by aaronesilvers** [comment]
Wearables are challenging as enterprise architecture within medical communities want to enable such devices to be clinical (as the requests turn into demands) and they need integration paths for near-zero configurations. 
I'm all for the most and the heaviest metal possible. But some people are really into ambient. 
-a-

---
#fromMobile





On Sun, Jun 21, 2015 at 5:44 AM -0700, "Jason Lewis" <notifications@github.com> wrote:












@aaronesilvers 




The rationale for separating out the data model (what information constitutes a statement and the nomenclature for it's data model elements) from the data binding (in our current case, JSON) is to allow for (eventually) other data bindings to be employed.




There's a practical way to deal with an intractable lack of comprehension for the need of add'l data-bindings, while also dealing with the clients that would require them; we've been doing this with wearables, beacons, etc., through the time-honored tradition of throw more metal at it!



When one can't be bothered to reduce the space or time complexity of a procedure, thank's to Moore's law, we can now just throw more hardware at the problem for pretty cheap. Hence, when dealing with tiny BTLE devices, have them speak xAPI through a device that makes a Cray-1 look like a pocket calculator, fits in a pocket, and can run Java. 



I wish there was an animated GIF to convey this... I'm probably not looking hard enough... le sigh

**Comment by canweriotnow** [comment]
@aaronesilvers I know, and coming from a background dealing with the challenges of even basic wireless networking deployments in medical environments, it's more complicated than anyone wants to acknowledge. Take last month's Global Cities thing: the final solution was to make Android phones a man-in-the-middle (in a good way) vector. But that was for EMS, and once you get _inside_ the hospital, there are even more concerns. 

I'm sure you know, my appeal to Moore's Law was, as most things I say or do, a HHOS (ha, ha, only serious) response; 'metal' heavier than Motörhead can fit in a pocket (srsly, I thought my phone had more power than a Cray-1, turns out it has more FLOPS than a Cray-XMP. Now that's cray-cray).

At the same time, sometimes it doesn't matter how hard your toilet can flush when you've got 5mm pipes; you need to break up that turd or things are going to back up.

Sometimes, especially in clinical or scientific environments, we need to deal with tiny pipes; pipettes, even. And then when we start talking about sensors, the toilets get smaller. 

I don't know where this bathroom metaphor came from, but bear with me.

So we can only slide tiny turds through tiny pipes, but have a voracious cesspool (LRS) at the other end. 

If the pipes were the only problem, packet-switching would be enough; TCP is only going to handle packets of a certain size, generally of a sub-Statement size; we just send 2 or 2k packets. 

But if we have to wait to send them - and with TCP we can't really throw out a packet until we know it's been properly received - the sender needs enough buffer space to hold onto them.

So we have a few options:

1. Stop caring if the message arrives
2. Make the message smaller

We can do 1. by using UDP instead of TCP, but then we also get to drop down to the transport layer and work our way back up, as HTTP is erected on the edifice of TCP.

We can do 2. via compression but a) we're already compressing the hell out of most HTTP traffic and get diminishing returns, and b) if we want to compress it in a novel way, both ends need to know what compression algorithm is being used.

Or, we can do 2. via data bindings like msgpack or novel binary octet-stream MIME types with built-in novel compression schemes, or doing creative things with the byte stream from wearable sensors without a MiTM-(what's the opposite of 'attack'?)

So we can start there.

You know, In the Ruby community, there's this saying, Matz Is Nice So We Are Nice (MINSWAN). 

I grew up on comp.os.linux, though, and sometimes I miss the degree of... "this not a terrible solution, this is just bad engineering so you are a bad person and should feel bad" that happened there. I'm not saying it was right, it was a certain culture.

But here, @aaronesilvers is nice so we are nice. AINSWAN.

**Comment by andyjohnson** [comment]
Document has been restructured
