### ISSUE TITLE
is correct response pattern exhaustive?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#746]
For long fill in type questions, it's common for answers to be marked by logic more complex than comparing the learner's answer to a list of options. For example the marking code might look for specific key words and ignore the rest. In these cases, could correct response pattern be used to return a list of exemplar responses? 

For example, consider this question on Udacity: https://www.udacity.com/course/viewer#!/c-ud837/l-4027328704/e-4247268609/m-4203488642

The correct response pattern might be something like:
```
[
    "It says Happy Birthday in the top left.",
    "There's a small grey box.",
    "The box is 150dp wide.",
    "The box is 75dp tall."
]
```

Clearly there are many other strings of text that would be marked as correct by that Udacity question, but that list conveys a range of possible correct answers, therefore I think this is a useful correct response pattern to report. 

I did also consider that the list could represent the key words that are being looked for, however this does not work with complex marking algorithms like the Udacity example. E.g. "box is 75dp tall" is marked incorrect ("the" is important) whereas "the box is 75dp in height" and "the box is 75dp from top to bottom" are marked correct. These sorts of marking algorithms are only going to get cleverer in the future. 

Or should we not report a correct response pattern in this scenario? The consumer of that data then build up a list of possible correct answers that have actually been given based on the result.response property statements marked as correct. 

I don't believe SCORM 2004 is clear on this either (see section 4.2.9.1 of the RTE).

**Comment by andyjohnson** [comment]
So from the SCORM 2004 4th Edition RTE 4-48:  “fill-in”:  The interaction requires the learner to supply a short response in the form of one or more strings of characters.  Typically, the correct response consists of part of a word, one word or a few words [1]. 

What I think this means is that the correct response pattern would have a condition where it is correct if:
 "happy", "birthday", "top", and "left" all appear
"gray" and "box" appear
 "150", "dp", and "wide" all appear
or "75", "dp", and "tall" all appear.

I'd lean towards leaving the pattern up to the evaluating content unless it could be clearly articulated, but with machines getting so much smarter, suggesting they try to create these somewhat archaic data structures seems counter-productive. 

Sorry for the long intro, but I think what you are asking is essentially could "correct responses" be hijacked to show examples of correct responses rather than the actual logic behind the correct responses, to which I'd say no ;) I'd go even further to suggest that in many cases, if correct responses can't match exactly, not to use it at all.

I'd instead hope that a CoP would create some sort of result extension to offer the learner hints on assessments in addition to other things to make xAPI reporting on interactions/assessments better!

**Comment by garemoko** [comment]
I'm more asking about whether or not correct responses pattern was intended to always be a comprehensive list. Sounds like you're saying "yes"?

**Comment by andyjohnson** [comment]
I think it depends on the type, for "fill-in" it is actually more of a pattern - like they need to use 3 of these 5 words in order for it to be correct.  If it were "multiple-choice" it is literally a set of options, one of which needs to be correct, but could show the learner different inputs to that choice.  In either case, I think the information provided within correct responses needs to be sufficient to dictate if the provided answer is correct or incorrect.

**Comment by garemoko** [comment]
Dictate to a human or to a machine? Does the correct responses pattern need to be precise enough for the reporting tool to mark the question (I don't think it does) or just display useful information to a human viewing the information?

**Comment by andyjohnson** [comment]
It is precise enough to dictate to a machine, but SCORM does allow GetValue so it was also intended to be able to provide feedback (likely to instructors).  I don't recommend we get into testing any of this, but if we wanted to stick to the traditional (IEEE) use of these in fill-in types, it is that the pattern has to match tokens exactly to illicit a correct response.  Note that SCORM doesn't actually tie the correctness with the learner response and correct response pattern:  " The LMS cannot make any judgments of the result for the learner response of the interaction unless reported otherwise from the SCO." RTE-4-60

**Comment by garemoko** [comment]
I think you've convinced me. So I think the action here is to add some text explaining that correct response pattern is limited to applications with simple marking logic.
