### ISSUE TITLE
Learning Experiences or All Experiences?

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#753]
The second line of the current introduction states:  
> This specification was developed with learning experiences in mind, but many other kinds of experiences could be tracked using xAPI.

I suggest that we remove this sentence as it detracts from what I perceive is the central mission of the specification document - which has to do with describing and tracking learning experiences.  I am sure that many users will come to the conclusion that the xAPI could be very useful in other contexts - but I think in our exposition we should talk only about learning experiences

**Comment by NickWashburn** [comment]
This learning experience thing may seem really nit picky...but I disagree. Med to Large ecosystems are finding a unifying concept in the LRS...There are already other experiences being tracked. xAPI is being used like Google Analytics to easily track activity streams into LRSs, track usage of social media feeds to award points in collaborative activities. In a project of mine we are tracking the usage of a software as we are doing inline training in the software. We are also working on a script tag that you can just drop on a page.

I would say 
*but many other kinds of experiences could be tracked using xAPI.*
like this 
**but many kinds of experiences may be tracked using xAPI.** - thats the nit picky part I think this intro is reading pretty good, cudos

**Comment by garemoko** [comment]
I think there's a lot of feeling in the opposite direction too - that xAPI should be able to be used to track any experience, especially work tasks the might demonstrate competency (or lack of). 

IMHO this sentence is a good compromise.

**Comment by rswetnam** [comment]
I think it's great that the xAPI framework is being used to track
experiences other than those just learning experiences.  I guess my concern
is about diluting the focus of the project/mission/brand.  When your focus
is on everything, there is the danger that you have a lot more work to do,
more stakeholder groups to satisfy and a lot less credibility in the domain
that you were originally focusing on.

What does IMHO mean?

On Tue, Sep 15, 2015 at 2:58 AM, Andrew Downes <notifications@github.com>
wrote:

> I think there's a lot of feeling in the opposite direction too - that xAPI
> should be able to be used to track any experience, especially work tasks
> the might demonstrate competency (or lack of).
>
> IMHO this sentence is a good compromise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/753#issuecomment-140342194>.
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118

**Comment by andyjohnson** [comment]
In terms of the entire work of xAPI, we've always been focused on learning first, but open to the idea that xAPI could be used in a variety of ways.  One way this is currently strongly embedded in xAPI is in results, where we have score, completion, and success.  We also define different interaction types in accordance to how they are done within current e-Learning.  This is a pretty strong push and I think it is acceptable for establishing our emphasis on learning as the primary focus of xAPI.  I also worry if we don't focus in learning (our domain) that we lose credibility.

**Comment by garemoko** [comment]
Literally: In My Humble Opinion

A better translation is simply "I think". I think I should try to use "I think" more often than "IMHO", IMHO.

**Comment by aaronesilvers** [comment]
To this end, I would at least mention “performance” if “learning" must be mentioned as a qualifier to experiences.

Learning is often intrinsic. We note the observation of it with xAPI, and we derive our meaning from the data that’s collected in terms of outcomes. We can’t address the intangible learning that takes place, but we can always talk about performance, because performance is evaluated by the how and the what.

Performance is a significant value proposition of xAPI for organizations and (imho) it’s at least as important as learning.

**Comment by rswetnam** [comment]
Thanks @garemoko - S (smile)

**Comment by NickWashburn** [comment]
Here are user stories or epics that would not be tracking learning experiences directly.

The system needs to report finite user experience via xAPI so that competencies can be established.

As an X educator/trainer I need X to report experience via xAPI so I can create and maintain a curriculum for X 

As a learning content creator I need to track X workflows and experiences so I can create training for X.

The system needs to deliver automated tutoring for X so that a first layer of help for well documented training tasks or remediation can help reduce the need for live trainers

As an administrator I need to track X experience/performance data so I can quantify an ROI effect of training

**Comment by garemoko** [comment]
Did we address this in discussing @rswetnam's introduction PR? Can this now be closed?

**Comment by aaronesilvers** [comment]
There seemed to be some objections, though off-thread. Not sure this is resolved.

**Comment by garemoko** [comment]
@aaronesilvers Looking at the introduction [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#10-introduction) what specifically needs to be changed and why? (Or who do we need to poke to answer that).

**Comment by aaronesilvers** [comment]
@garemoko from where this started in [issue 739](https://github.com/adlnet/xAPI-Spec/issues/739) I think we'd want to poke @jgoodell2 @rswetnam @NickWashburn just to make sure.
