### ISSUE TITLE
Explain why LRS is expected to use 'exact' when getting statements

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#760]
The GET Statements table says:

```An LRS requesting Statements for the purpose of importing them would use a format of "exact".``` 

We don't explain this any further anywhere, for example we have no:

* MUST/SHOULD requirements relating to this (maybe it's hard to test)
* Explanation of why it's important
* Explanation of how canonical definitions might be transferred between LRSs

Should we add some/all of those things?

**Comment by fugu13** [comment]
On the one hand, anyone implementing an LRS should immediately understand why. On the other, it isn't hard to add a quick reasoning.

There's absolutely no way to test it, as importing across LRSs isn't a defined action (or something easy to narrow in on), plus, I see no reason to not give LRSs the ability to experiment, so no MUST. Maybe a SHOULD, though since it isn't something that's actually defined in the spec, this is more an aside than a requirement.

It isn't possible to have "Explanation of how canonical definitions might be transferred between LRSs" as that isn't something that happens, and each LRS is allowed to come up with its own canonical definition procedures.

The reason is straightforward: "exact" is the same way the statements were sent in, so by using exact, you're getting the real statements. If you use "ids" you won't get a large amount of the information included in the statements, so you aren't importing the real statements. If you use "canonical", you're getting the other LRS's suppositions about inferences and possible outside information instead of the information in the original statements, so you aren't importing the real statements (and would quite possibly make incorrect conclusions if the other LRS had made any unwarranted changes, even if those changes were later corrected in the other LRS).

**Comment by garemoko** [comment]
On transferring canonical definitions, let me give you a real world use case: 

* Articulate Storyline 2.0-2.4 does not include any activity definitions in statements. Instead it provides those definitions as part of the tincan.xml file which is allowed as a source of canonical definitions (because the LRS can use any source). This is not a totally unreasonable idea in theory, though problematic in practice, which is presumably why Storyline 2.5+ does include definitions. 
* This works great when the LRS is part of the system that launches the content, e.g. SCORM Cloud or an LMS that uses SCORM Engine. 
* It's common enough that users of an in-LMS LRS would want to send statements out to an external LRS for reporting and analytics (e.g. Watershed - you can see this is a very real example!). 
* In this scenario if the analytics LRS only fetches statements by exact and does not also fetch the canonical definition, it does not get the activity definitions as they do not exist in the statements received.

Another similar scenario is where the second LRS receives a filtered subset of statements and that subset does not include definitions. 

Possible ways to fetch the canonical definition are fetching all the statements again as canonical or using the activity profile API full activity object GET.

**Comment by garemoko** [comment]
@andyjohnson - this issue isn't on your table of open patch issues. This one would be good to discuss on a call.
