### ISSUE TITLE
ETag requirements prevent use of gzip

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/xAPI-Spec#789]
xAPI defines specific ETags that must be used for responses: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-5

However, the HTTP RFC states that: `The ETag response-header field provides the current value of the entity tag for the requested variant.`

The upshot of these two requirements together is that systems conforming to xAPI MUST NOT offer gzip or other variants for responses. That's an unreasonable result so we need to do something about the requirement on the xAPI side. The most reasonable approach seems to be to just drop the requirement for the LRS to calculate the ETag in a specified manner. The downside is clients will no longer be able to figure out what the ETag "should be" based on the document they have, but based on the fact that popular software (Apache's gzip mod at least) modify the ETag, this is already something it's not safe for clients to rely on in practice.

Therefore I recommend we remove the following requirement:
`An LRS responding to a GET request MUST add an ETag HTTP header to the response. (The reason for specifying the LRS ETag format is to allow API consumers that can't read the ETag header to calculate it themselves.)`

**Comment by fugu13** [comment]
The calculation requirement was always a bit wonky, but I'm not sure we can remove it right away, as there may be clients relying on it. As you encountered, since we're using a strong ETag, it is required that resources returned be octet-equivalent, which could change not just by using gzip, but based on the level of gzip compression chosen.

Now, I'm pretty sure there are very few if any clients relying on it, but we'll want to carefully consider how much of a version bump will fit with this change, especially as there's no real way to *tell* if there are clients relying on it. Definitely not 1.0.3.

**Comment by fugu13** [comment]
Of course, any client relying on it (that isn't very badly written) would already need to have a fallback mechanism in place that would suffice for ETag behavior changing, so maybe that's enough cover?

**Comment by bscSCORM** [comment]
Yeah, I was on the fence about which version we should make this change in so I didn't make a recommendation on that. I've been going back and forth between "it's technically a breaking change" and "anyone relying on this behavior is probably broken already".

**Comment by fugu13** [comment]
Okay, so, thinking this through and continuing to add yet more posts, maybe we could say, since the existing standard totally precluded gzip, that the behavior described is only for when transfer encoding is omitted (or identity), and that when transfer-encoding is specified, the rule didn't apply anyways?

Plus note that we intend to remove the requirement to calculate the ETag a specific way in any situation in some future version.

**Comment by fugu13** [comment]
Strangely, while transfer-encoding definitely breaks ETags, and servers have built up around those assumptions, I'm not totally sure the RFC requires a change in ETags. Quoting the ETag section:

> A "strong entity tag" MAY be shared by two entities of a resource only if they are equivalent by octet equality.

> Transfer-Encoding is a property of the message, not of the entity, and thus MAY be added or removed by any application along the request/response chain.

(It mentions some modifications of that in 3.6, but as far as I can tell none of 3.6 would interact with ETags).

Since ETags only apply to the entities, not the message, and transfer-encoding only applies to the message, not the entities, they shouldn't interact. That they do in lots of existing applications may be some practical implication of other parts of the RFC or just how a bunch of servers and proxies ended up implementing stuff.

De facto requirements are still requirements, though ;)

**Comment by bscSCORM** [comment]
>Okay, so, thinking this through and continuing to add yet more posts, maybe we could say, since the existing standard totally precluded gzip, that the behavior described is only for when transfer encoding is omitted (or identity), and that when transfer-encoding is specified, the rule didn't apply anyways?

>Plus note that we intend to remove the requirement to calculate the ETag a specific way in any situation in some future version.

This sounds appealing, though I wonder what could happen if a proxy decided to request a gzip-ed version, and then unzip it to return it to a client that didn't request gzip (just to save bandwidth between the proxy and the LRS). The LRS would see that gzip was requested and this rule didn't apply, but the client wouldn't have requested it.

So at the very least, we should add `Clients SHOULD NOT* rely on this behavior`

**Comment by fugu13** [comment]
Works for me. Re: the example, seems like the LRS would have behaved defensibly, even if the proxy would have obliterated the evidence of it, so with the added text I think we're still fine. Smart proxies are always "at your own risk" anyways ;)

**Comment by garemoko** [comment]
I'm not following this 100% and I'm normally on the other side of a code library when interacting with this. In both TinCanJS and TinCanPHP (and presumably others) the library provides an etag value as part of whats returned by get functions, which I assume comes from the header. I expect that there are serval APs that take that value from the libraries and return it when sending modified data. 

In the Moodle launch plugin (which doesn't use a library for reasons of PHP version compatibility) the eTag is definitely [retrieved from the header](https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L543-L551) and then sent back to the LRS [when new content is PUT to the state](https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/launch.php#L72-L118). I'd be the first to admit that the Moodle launch plugin is open to PRs but it works today. 

Is what you're discussing going to break either of those two cases, or is the other behaviour (calculating the eTag yourself) the thing that would break? I have a nagging feeling at the back of my mind that I've seen that approach somewhere before too. Possibly (hopefully) it was an earlier version of the plugin or a test script that got changed/was written because of an old bug in Learning Locker when it was returning the same ETag for all documents. I'm not sure.

**Comment by fugu13** [comment]
No issues would be caused with libraries that rely on ETags found in requests (which is already the best way to handle things). Only a library that 1) precalculated an ETag and 2) didn't handle the situation where the ETag wasn't as expected (as they should already handle in case something else updates the resource) would have any fundamental problems with the change. They wouldn't even have problems there so long as they didn't request a gzip transfer-encoding, with the solution I proposed above.

**Comment by garemoko** [comment]
What if they handled the etag not being as requested by fetching the resource again and recalculating the etag again? Is that an endless loop presumably?

I guess that's still covered by the "don't request a gzip transfer-encoding" which presumably they wouldn't be in the current world. I think I'm starting to catch up.

**Comment by bscSCORM** [comment]
It's only calculating the ETag that would break, and only in the case of gzip being used. However, we're suggesting that version 2.0 would remove the LRS requirement to create an ETag via a defined method the client could duplicate, and therefore the "calculating" method should be abandoned as soon as practical. Also, I'm raising the issue that certain proxies could break client behavior even if the LRS was following the spec, so clients shouldn't rely on calculating their own ETag's anyway.

**Comment by brianjmiller** [comment]
As a library dev I welcome this change, only two of the ones I maintain do any sort of calculation, and in both cases they only do so as a back up approach.

* TinCanJS calculates when it can't detect an Etag in the response on a GET request which is probably just a safe guard against old IEs or poor LRS implementations.
* TinCanPHP calculates on the PUT side of the equation and that calculation would be overridden by a subsequent GET which is potentially informative of a feature I'd like to see added.

If we get to a point where the LRS can use its own means to generate the Etag then I'd like to see us include the generated Etag on saving of the document via an additional header so that the client doesn't have to round trip to get the value it just stored (which was probably the intent of the original requirement). The returned value couldn't be the Etag of the response of the save (particularly when there is no content) but we could include an `X-Experience-API-Etag` (alternate names acceptable) header with the calculated value that clients could leverage if they desired.

**Comment by canweriotnow** [comment]
I feel like this came up long ago and far away... one suggestion, IIRC, was instead of using ETags (which I've long detested), adding a checksum header that could be used to validate/compare the pre-compressed and decompressed values instead of relying on HTTP server ETag generation? 

Of course, checksums would require something like standardizing or stripping whitespace for the req/response bodies so they would match, but I think this might be a possible resolution so we don't lose out on compression at the expense of implementing (IMHO) one of the poorer web standards.

**Comment by fugu13** [comment]
@canweriotnow in the discussion above we reached consensus that a mild relaxing of the ETag calculation requirement when gzip transfer encoding is in use makes sense and wouldn't cause compatibility issues, so there's no need to make the large spec change of an entirely new header.

**Comment by fugu13** [comment]
I can work on a PR for this

**Comment by fugu13** [comment]
I've opened a PR with a fix for this. Btw, if people want to include an integrity check not subject to transfer-encoding, Content-MD5 is a good way to go.
