### ISSUE TITLE
Document Structure Suggestions

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#796]
I would like to suggest some changes to the spec that will provide a bit more context to the new reader and which more clearly differentiate between Part One which I think is really about providing an overview of the whole xAPI ecosystem and Part Two which talks about the nuts and bolts of the application programming interface.  By taking technical details out of part one, we give the general reader and the more technical ones, a clearer understanding of the rationale behind the initiative.

# Part One:  Overview of the Experience API
### 2.1 The Major Components
This section would describe in broad terms the structure and function of the major components of the ecosystem - i.e. Activity Providers, Learning Record Stores and Consumers.  It might include some sample use cases and diagrams.
### 2.2 Profiles and Communities of Practice
This includes the current section plus some additional description about how COPs fit into the overall system.
 
# Part Two: The Application Programming Interface
## 1.0 Introduction
An Application Programming Interface or API is a set of rules the conformance to which allow different computer programs to communicate with each other.  Part Two of this document sets out those rules for the Experience API which are categorized as follows:
- Common Language for Exchanging Data (JSON) (*moved from Part One*)
- Criteria for Conformance (Must/Should/May)(*moved from Part One*)
- Guidelines for Interpreting Descriptive Text and Tables (*moved from Part One*)
- The Grammar of Communication - Statements, MetaData and Special Types and Rules (*currently in Part Two*)

**Comment by garemoko** [comment]
@rswetnam thanks for this. My reading of this suggestion is that you're proposing moving the current sections 2 and 3 from part 1 to part 2. 

I'm against moving section 2 because this information about how to read the document applies to both parts 2 and 3 so really does belong in the introduction. 

I can see that section 3 would actually make a lot of sense as an introduction to part two and I guess if it was done as an unnumbered heading, it could be done without re-doing all of the numbering for part 2 again. It would mess up part 1's numbering and table of contents though. 

We do need to settle on a structure and stop making changes for this version at some point though. IMHO that point has really already been passed but I wouldn't oppose a well done PR that moved part 1 section 3 and updated all the links and TOC and didn't conflict with any other open PRs. 

In response to the general goal of taking all the technical stuff out of part one, do remember that the specification document itself does not have to do everything. There's are lots of bloggers and website owners in the community who write great introductions and explanations. Really the specification document is for those who already have been sold on the concept of xAPI and now want to implement it. Even then, if they are creating an Activity Provider they'll likely be using it as a reference source alongside some tutorial and code example, using a library that handles much of the spec.

**Comment by rswetnam** [comment]
@garemoko Thanks for your comments.  I sympathize with your desire to settle on a structure and stop making changes to this version - and would not be averse to seeing my suggestions considered for the next version.  

That being said, I think it important that you understand the frustration that I had as a somewhat technical reader who came to this document to use it for building a small LRS.  What I found was that there was no context or overall explanation of how the pieces fit together and it was only after a considerable time and participation in this working group that I am coming to that understanding.  For example, even now, there is no introduction to the application programming interface.  The reader is introduced to in by being presented with the table of definitions in Part One Section 4.   This is somewhat akin to reading an introductory book on chemistry and having the first chapter as the Periodic Table.  It might look look right to the experienced chemist - but the new reader I suggest would be overwhelmed.

My suggestion for taking the technical details out of the first part is so that it can be used to explain the rationale behind the rules of the api - something that I think is useful for the technical reader.

On a practical note, I think that an Introduction in Part Two could be substituted for 1.0 Documents which is three sentences long and should not, I suggest be a complete chapter in itself.  This would minimize the disruption to the numbering scheme.

Again, I understand the need to move forward and not keep rearranging the deck chairs - but I think we do need to consider the needs of new readers, even technical ones, who are not already deeply steeped in the spec.

**Comment by garemoko** [comment]
Thanks @rswetnam as i said, I;m not adverse to a PR to move section 3 if you get it in quick :-)

The documents section, though short, does deserve it's own section. Documents are very important, there's just not much to say about them in regards to data structure because any structure is allowed.

**Comment by garemoko** [comment]
Can this now be closed or does it need more discussion or a PR?

**Comment by andyjohnson** [comment]
For 1.0.3, I'm going to call this done.  Always open to more suggestions in the future versions as well as companion documents.

**Comment by rswetnam** [comment]
Please close - though I think it bears revisiting once the dust has settled.

On Wed, Mar 16, 2016 at 5:08 AM, Andy Johnson <notifications@github.com>
wrote:

> For 1.0.3, I'm going to call this done. Always open to more suggestions in
> the future versions as well as companion documents.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/796#issuecomment-197288352>
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118
