### ISSUE TITLE
Term for Application that Consumes LRS Data

### ISSUE THREAD

**Issue by rswetnam** [adlnet/xAPI-Spec#832]
Section 5.0 explains and shows graphically how different pieces of xAPI can fit together.  Two of these are defined - Activity Provider and Learning Record Store.  The section also says that the LRS can be queried by a Data Analysis tool - for which there is no definition.  

I think that we either need to either:
* define "Data Analysis Tool", 
* specify a term for and define this component
* drop the term Data Analysis Tool from the high-level explanation of how the pieces fit together.

I've also heard the term consumer in one of the online meetings to refer to this component. 
 
My suggestion is to use the term Statement Processor and define it as a software component which accesses data from an LRS and processes and formats that data as required by users.  I think it's useful to have the term "Statement" in the definition to remind us that we are processing statements of learning experience - but could certainly be convinced otherwise.

In any case, I think we need to fill this gap.

**Comment by andyjohnson** [comment]
I'm fine dumping "Data Analysis Tool", it was really a placeholder for something better.  I'm going to start on the revision of those graphics today.  We've already got a Producer/Consumer concept going, so I'd rather say Statement Consumer as I think we can safely say an LRS is not a Statement Consumer, which I think is the distinction we are going for, right?

**Comment by brianjmiller** [comment]
I've always held (which may or may not be supported by the definition in the spec) that Activity Provider is any system communicating with the LRS, not just one that stores statements, so a "data analysis tool" is an Activity Provider (which is a name I really can't stand in and of itself). So, I'd ask why can't Activity Provider be used for all the pieces communicating with an LRS?

I'd also be cautious of focusing too heavily on "Statements", which starts to imply that something doing analysis can't (or won't) use the other APIs, particularly the metadata ones which I think would be over reaching.

**Comment by brianjmiller** [comment]
@andyjohnson LRSs are statement consumers when there is an LRS to LRS transfer.

**Comment by rswetnam** [comment]
I've used the term LRS Consumer in my revised Pull Request and defined it
as "a software program or component of a program which is able to access
data from Learning Record Stores, process that data and make it available
to users or other program".  I hope that this is sufficiently generic and
addresses your concerns.

On Wed, Dec 2, 2015 at 8:03 AM, Brian J. Miller <notifications@github.com>
wrote:

> @andyjohnson <https://github.com/andyjohnson> LRSs are statement
> consumers when there is an LRS to LRS transfer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adlnet/xAPI-Spec/issues/832#issuecomment-161345385>.
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118

**Comment by fugu13** [comment]
I'm fine with a term that reflects consuming but not providing data, but I'm leery of "LRS Consumer" due to it having LRS in the name and the existing use of Consumer for OAuth Consumer (and Metadata Consumer). I see in a number of places we use consumer in a more relaxed way, and I'd like to see those cleaned up, too.

I'd lean toward going more generic, with something like Client, which I think we already use some places, and then including clarifying language as needed. For example, saying an LRS can be queried by Clients with many different purposes, such as data analysis.

**Comment by canweriotnow** [comment]
I'm also kinda leery of using AP to refer to reporting or analytics tools, as they're not providing activities, they're munging data from the LRS.

That is, unless, your analytics tool is also reporting usage data on itself back to the LRS via xAPI, in which case it's _also_ an AP, but that's kind of orthogonal to its role as an analytics tool, and that kind of xAPI-ouroboros situation is probably not widespread at this point.

**Comment by canweriotnow** [comment]
Upon further reflection and discussion, I'm not certain we need a "spec" term for a consumer of xAPI data... AP makes sense in its current context, and LRS makes sense, but since it's just JSON, it's a reasonable assumption that anything consuming data _out_ of an LRS (that isn't just another LRS) will be munging data into some other format for analysis purposes because... well, xAPI is a well-designed structure for data interoperability, not analysis. That's a separate concern. 

I like @fugu13's generic suggestion of Client, since it fits with existing HTTP-transport technologies, isn't limiting, and is distinct from AP (although an AP could be a union or intersection with the Client set).

But anything that is "non-LRS-to-or-from-LRS" makes sense as Client, rather than the aforementioned LRS))<>((LRS film clip.

**Comment by garemoko** [comment]
There are cases where we need to talk about how the values of certain properties are intended to be interpreted and thus refer to systems that read statements (I don't think we ever need to talk about systems that interpret documents, but I could be wrong).

I dislike "client" for this purpose because I see client as broader, incorporating any system interacting with the LRS in any way. 

I don't have any suggestions for a better term though.

**Comment by garemoko** [comment]
In case it's helpful, here's some graphics I made during a discussion on an earlier call: https://github.com/adlnet/xAPI-Spec/issues/726#issuecomment-149993897

**Comment by garemoko** [comment]
On the call Dec 16 we agreed on the term "Learning Record Interpreter" as a system that derives meaning from statements. (This would also apply to a system that derives meaning document if we ever have language around how to interpet the values of properties in documents.)

**Comment by garemoko** [comment]
This is resolved I think.

**Comment by andyjohnson** [comment]
Agreed.
