### ISSUE TITLE
Is LRS responsible for validating that language maps use valid keys?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#854]
Language map keys are RFC 5646 Language Tags but we have no language around where or not the LRS has to validate these tags. A possible interopterability problem could occur if an activity provider uses a non-RFC 5646 language tag which is not validated by one LRS but is validated by another further down the chain.  

If we do add any requirements on this it would be a MUST or MUST NOT for the LRS to do the validation. This is therefore a minor issue, though we could add a SHOULD* as a patch. 

Looking at RFC 5646, it seems like validation is impossible unless we also require that language tags must be listed in the IANA registry OR use the reserved private language tag characters. For that reason, my preference is to say that using good language tags is the responsibility of the activity provider and MUST NOT be validated by the LRS.   

The context of this issue is that I've come across an activity provider using "this" as a language map key and it's not rejected by Watershed. I don't know what other LRSs do, but presumably its not in the conformance tests.

**Comment by fugu13** [comment]
LRSs are required to validate types, which would apply here. They're given some leniency by the data constraints section, which emphasizes that the minimum validation allowed is the sequence of token lengths:

> The LRS MUST at least validate that the sequence of token lengths for language map keys matches the RFC 5646 standard.

That's because maintaining a database of allowed language tag values is prohibitively complicated, and there are numerous allowances for extensions and private use segments in 5646.

In the case of 'this', a 4-length token is allowed as the first token, though 5646 reserves it for future use.

If you want to check something that should be rejected, the first token can be no longer than 8 characters. Something unusual that should be accepted is i-klingon.

**Comment by garemoko** [comment]
Closing this since the section quoted by @fugu13 already covers this issue, I just missed it.
