### ISSUE TITLE
More examples of correct response patterns and their meanings. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#867]
I'm seeing a few APs get correct response patterns wrong when there is more than one correct answer e.g 

```
[
  "Some right answer[,]Another right answer"
]
```
This means that both the answers are required for the response to be correct. 

What is actually intended is that either answers are correct:

```
[
  "Some right answer",
  "Another right answer"
]
```

Without actually looks how clear the spec is currently on this, I wonder if we can make it even more explicit.

**Comment by andyjohnson** [comment]
2/17/16 - Think examples are sufficient, but will validate on next run through part 2.

**Comment by canweriotnow** [comment]
Any consideration to some convention on regex literals for CRPs? JSON doesn't have a regex literal IIRC, but even a string pattern like `"regex:/^my.+puppy$/"` could be used by an LRS to match any response starting with "my" and ending with "puppy" as long as there were intervening characters. 

I think this occurred to me because we have these keys of correct response pattern, score, result, response, etc., and if the LRS isn't able to make any judgment on them, all they can tell us is that the AP is faulty, i.e., if an AP submitted result: success, response: birds, correct responses pattern: anything but birds, the LRS can't judge. Maybe we should accept the statement but in 1.(x > 3) or 2.0 let the LRS flag the statement with, I dunno...

![No way](http://media.tumblr.com/tumblr_mf42cccUGy1qlyey2.gif)

Thoughts?

**Comment by garemoko** [comment]
Yeh, right now the correct response pattern isn't designed for the LRS to make judgements or actually assess questions. 

That sort of thing feels like to me it would be a separate spec, maybe as a profile like cmi5 and covering similar scope to something like QTI so that the LRC could actually replicate the complete question. In that spec, using regex for correct response patterns seems like a good call.

**Comment by canweriotnow** [comment]
@garemoko Yeah, that's why I assumed it would be a "breaking" change on some level; but the "result" entity has the capability to let the LRS make the judgment call, or at least reject self-contradictory statements, it could either help with LRS consistency or move some of the burden from the LMS to the LRS, which I think (from a business perspective) helps the "stickiness" factor for commercial xAPI... not necessarily something to jump into now, but I wanted to suggest it for future consideration, as I think it's a potential win for xAPI in general.
