### ISSUE TITLE
ISO 8601- are **unnecessary** leading zeros permitted?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#874]
In short: is the following duration valid, or should it be rejected by LRSs?

`PT0005M25S`

ISO 8601 section 3.6 says: 

"If a time element in a defined representation has a defined length, then leading zeros shall be used as required."

But does that mean they can't be used when not required? If you can use them, is there any limit on string length?

**Comment by andyjohnson** [comment]
I think it should be rejected.  I think this is referring to the fact that in a TimeStamp with 2016-02-29T - you would need the 0 in front of the 2 because of the designation of the two spaces for DD.  (I haven't bought the spec, so I can't read this directly and this explanation is partially speculative)

**Comment by andyjohnson** [comment]
more discussion can be found in #897

**Comment by garemoko** [comment]
yeh, I;m actually going to close this in favor of #897 since what's proposed there would fix this.

**Comment by garemoko** [comment]
Re-opening, since RFC 3339 doesn't cover durations.

**Comment by garemoko** [comment]
I'm currently leaning on the side of extra leading zeros being ok, and us not requiring any change to the spec. This is mainly because Watershed (based on SCORM Engine) accepts them without difficulty. I don't know what other LRSs do.

**Comment by fugu13** [comment]
As far as I can tell, leading zeros on fields without a defined width are totally okay by 8601
