### ISSUE TITLE
IRI Metadata

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xAPI-Spec#891]
Need to update this section, https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#miscmeta, to be consistent with proposed vocab companion spec and primer:

https://github.com/adlnet/companion-specification-for-xapi-vocabularies/blob/master/SUMMARY.md

https://github.com/adlnet/experience-xapi-vocabulary-primer/blob/master/SUMMARY.md

Instead of returning JSON, now return JSON-LD if requested. If IRI is requested through browser, then the IRI resolves to the HTML version.

**Comment by garemoko** [comment]
Given that this is all "SHOULD" I'm ok with doing this as a patch, so long as when "application/json" is requested, there's no changes to what we currently recommend (for reasons of backwards compatibility). 

"For any of the identifier IRIs above the Metadata Provider SHOULD ensure that this JSON metadata available at that IRI when the IRI is requested and a Content-Type of "application/json" is requested."

**Comment by jhaag75** [comment]
it would be application/ld+json instead of application/json

it might need to be a new requirement as part of 1.0.3 or later version rather than a patch...I assigned this to me, let me try to put together some suggestions and we can review

**Comment by garemoko** [comment]
So, what I;m envisaging is that a metadata consumer can request either html, application/ld+json, or application/json. if they request application/json they get what the spec recommends today, if they request application/ld+json they get whatever it is you're proposing. Metadata consumers would be encouraged to supply both.

**Comment by jhaag75** [comment]
The vocabulary working group discussed this at length (mostly @fugu13  and I), and we believe providing granular json metadata for each term is not feasible and provides no value. That's why nobody is really supporting it. What we propose in the vocab spec is to provide the complete vocabulary in one JSON-LD file and to remove the requirement for individual json files. 

This makes populating a registry and other vocabulary interfaces much easier, but also is easier for those publishing vocabularies as dataset. It is easier to maintain and more likely to be supported. 

If we are to remove the json requirement for IRI metadata do you think that is a breaking change and should be in a new version? Could it be part of 1.0.3?

**Comment by garemoko** [comment]
@jhaag75 I think it's probably ok, but would like to reflect on it more. I'm thinking it's ok for 1.0.3 because:

* It's a recommendation not a requirement
* Few people are actually hosting the json metadata
* I'm not aware of anybody using hosted metadata (possibly some are using metadata from registry, but I think they might be going direct to registry anyway). 
* There's nothing to stop people continuing to host metadata for individual identifiers even if we remove the recommendation. 

I'm interested in @brianjmiller's thoughts since I imagine this would/could/should/might affect Registry.

**Comment by jhaag75** [comment]
Well the difference is that it is that it would be a requirement now to support resolving IRIs for verbs and activity types, and to provide a minimum of HTML and one other representation RDFa (embeded in HTML) or JSON-LD. 

https://github.com/adlnet/companion-specification-for-xapi-vocabularies/blob/master/vocabulary_implementation_requirements.md

I think perhaps #7 and #8 MUSTs would need to be changed to SHOULD*

**Comment by garemoko** [comment]
I'm not sure how it would work as a requirement rather than a recommendation. Who would the requirement be aimed at? Would we essentially end up with a tautological "Metadata Providers MUST be Metadata Providers"?

Or would we ban the hosting of application/json metadata unless json-jd is also available? That's a breaking change and seems counter productive since json definitions are better than no definitions. 

Or would you go so far as to say that statements MUST only use identifiers where a JSON-LD representation of all IRIs has been hosted? That would be a significant breaking change and push the spec to 2.0. (it'd also be IMHO a terrible idea, but we don't need to get into that now).

**Comment by jhaag75** [comment]
It is applicable to anyone creating new vocabulary terms (Verbs or Activity Types) for xAPI. It is also applicable to any individuals or organizations developing applications for publishing, storing or retrieving vocabulary identifiers and definitions, or any other types of services that need to query the semantic meaning of xAPI vocabulary data. 

I think the hosting of JSON files is fine for versions before 1.0.3. We would make this a new requirement as of 1.0.3 and figure out what to do with legacy IRIs such as Activity Streams verbs moving forward. But this new requirement and vocabulary guidance applies to any new Verb or Activity Type IRIs. 

I agree with your last paragraph. If we require statements to only use identifiers that returned JSON-LD that would be a breaking change and that's not what is being proposed right now. It just applies to any new vocabularies. We have done this for the ADL vocabulary, IEEE ADB Profile, Across X Profile, and working on others. The registry would require a big update to support it, but it existed before the requirement. I think eventually we want to have a discussion on what to do with Activity Streams IRIs, updating recipes to a new version, and how to update the registry in a pragmatic manner. I talked with Brian some about this previously, but he was waiting on us to put out this document before we could have any further discussion. In the meantime, I think updating the IRI Metadata section to reference the vocab companion document would be a good place to start if we want people to adopt this approach and other best practices (e.g. IRI Design).

**Comment by garemoko** [comment]
I propose removing the patch label because there's no clear decision about a patch change here.
