### ISSUE TITLE
Markdown href Best Practices

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xAPI-Spec#907]
I just wanted to validate that as a part of the document sweep that all internal references (internal being hosted on this GitHub site) should not use <a/href> and instead use the markdown [ ] ( ) format.

Are there any exceptions?  Any expansion?

**Comment by andyjohnson** [comment]
Ok, so the issue text didn't come through well because of the syntax I used.  As I see more and more external links with the markdown brackets and parenthesis used, I want to validate that all links should be done this way instead of using anchors, html tags, and hrefs.

**Comment by garemoko** [comment]
@andyjohnson The pattern I follow is to use markdown everywhere except inside tables. 

This is because we currently use HTML for tables which means that all markup inside tables (including links) needs to be HTML. If you put markdown inside HTML it doesn't render. 

We could move the tables to markdown tables but its a big job and would need to be checked very carefully. See https://github.com/adlnet/xAPI-Spec/issues/829

**Comment by andyjohnson** [comment]
Ok, I'm otherwise ready for a big Part 2 PR.  I'm going to eliminate any non-table hrefs and convert to markdown.  Thanks @garemoko

**Comment by garemoko** [comment]
Does this need to remain open or can it wrap under #857?
